/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DBModel;
import model.IModel;

/**
 *
 * @author Örs
 */
public class Foablak extends javax.swing.JFrame {

    private IModel model;
    
    public Foablak() {
        initComponents();
        
        setLocationRelativeTo(null);
        setTitle("Maki Könyvtár Adatbázis");
        
        String connURl = "jdbc:mysql://localhost:3306/library";
        String user = "****";
        String pass = "****";
        
        try {
            Connection conn = DriverManager.getConnection(connURl, user, pass);
            /*itt csinálok egy connectiont*/
            model = new DBModel(conn);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(),
                    "Adatbázis Hiba", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Kilep = new javax.swing.JMenuItem();
        jMIKonyvtariTagok = new javax.swing.JMenu();
        jMIKTagok = new javax.swing.JMenuItem();
        jMIKonyvek = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Fájl");

        Kilep.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        Kilep.setText("Kilépés");
        Kilep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KilepActionPerformed(evt);
            }
        });
        jMenu1.add(Kilep);

        jMenuBar1.add(jMenu1);

        jMIKonyvtariTagok.setText("Adatok");

        jMIKTagok.setText("Könytári Tagok");
        jMIKTagok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIKTagokActionPerformed(evt);
            }
        });
        jMIKonyvtariTagok.add(jMIKTagok);

        jMIKonyvek.setText("Könyvek");
        jMIKonyvek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIKonyvekActionPerformed(evt);
            }
        });
        jMIKonyvtariTagok.add(jMIKonyvek);

        jMenuBar1.add(jMIKonyvtariTagok);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KilepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KilepActionPerformed
        if(model != null){
            try {
                model.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(),
                        "Adatbázis Hiba", JOptionPane.ERROR_MESSAGE);
            }
        }
        System.exit(0);
    }//GEN-LAST:event_KilepActionPerformed

    private void jMIKTagokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIKTagokActionPerformed
        KonyvtariTagok ktagok = new KonyvtariTagok(this, true, model);
        ktagok.setVisible(true);
    }//GEN-LAST:event_jMIKTagokActionPerformed

    private void jMIKonyvekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIKonyvekActionPerformed
        KonyvekDialog kd = new KonyvekDialog(this, true, model);
        kd.setVisible(true);
    }//GEN-LAST:event_jMIKonyvekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Kilep;
    private javax.swing.JMenuItem jMIKTagok;
    private javax.swing.JMenuItem jMIKonyvek;
    private javax.swing.JMenu jMIKonyvtariTagok;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
