/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Frame;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.IModel;
import model.Tagok;

/**
 *
 * @author Örs
 */
public class KonyvtariTagok extends javax.swing.JDialog {

    private IModel model;
    private Frame parent;
    private List<Tagok> tagok;

    public KonyvtariTagok(java.awt.Frame parent, boolean modal, IModel model) {
        super(parent, modal);
        initComponents();

        this.model = model;
        this.parent = parent;

        setLocationRelativeTo(parent);

        updatelist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstKonyvtariTagok = new javax.swing.JList();
        btnUJ = new javax.swing.JButton();
        btnSzerkeszt = new javax.swing.JButton();
        btnTorol = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstKonyvtariTagok.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstKonyvtariTagok);

        btnUJ.setText("Új");
        btnUJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUJActionPerformed(evt);
            }
        });

        btnSzerkeszt.setText("Szerkeszt");
        btnSzerkeszt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSzerkesztActionPerformed(evt);
            }
        });

        btnTorol.setText("Töröl");
        btnTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTorolActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSzerkeszt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUJ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTorol, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOK, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(45, 45, 45))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnOK, btnSzerkeszt, btnTorol, btnUJ});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSzerkeszt)
                        .addGap(18, 18, 18)
                        .addComponent(btnTorol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOK))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnUJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUJActionPerformed
        TagokUJSzerkesztDialog tuszd = new TagokUJSzerkesztDialog(parent, true, null);
        tuszd.setVisible(true);

        if (tuszd.isMentes()) {
            try {
                model.addTag(tuszd.getTag());
                updatelist();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(),
                        "Adatbázis Hiba", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUJActionPerformed

    private void btnSzerkesztActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSzerkesztActionPerformed
        Tagok selected = (Tagok) lstKonyvtariTagok.getSelectedValue();

        if (selected != null) {
            TagokUJSzerkesztDialog tuszd = new TagokUJSzerkesztDialog(parent, rootPaneCheckingEnabled, selected);
            tuszd.setVisible(true);
            if (tuszd.isMentes()) {
                try {
                    model.updateTag(tuszd.getTag());
                    updatelist();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage(),
                            "Adatbázis Hiba", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Válassz ki egy személyt a szerkesztéshez",
                    "Adatbázis Hiba", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSzerkesztActionPerformed

    private void btnTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTorolActionPerformed
        Tagok selected = (Tagok) lstKonyvtariTagok.getSelectedValue();
        
        if(selected != null){
            int valasz =  JOptionPane.showConfirmDialog(parent, "Biztos hogy Törölni akarod a kiválasztott személyt?", 
                    "Törlési megerősítés", JOptionPane.YES_NO_OPTION);
            if(valasz == JOptionPane.YES_OPTION){
                try {
                    model.removeTag(selected);
                    updatelist();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Válassz ki egy személyt a szerkesztéshez",
                    "Adatbázis Hiba", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else {
            JOptionPane.showMessageDialog(rootPane, "Válassz ki egy személyt a Törléshez",
                    "Adatbázis Hiba", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTorolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSzerkeszt;
    private javax.swing.JButton btnTorol;
    private javax.swing.JButton btnUJ;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstKonyvtariTagok;
    // End of variables declaration//GEN-END:variables

    private void updatelist() {

        try {
            tagok = model.getAllTag();
            lstKonyvtariTagok.setListData(tagok.toArray());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(),
                    "Adatbázis Hiba", JOptionPane.ERROR_MESSAGE);
        }
    }
}
